/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.example.sudoku;

public final class R {
    public static final class anim {
        public static final int cycle_7=0x7f040000;
        public static final int shake=0x7f040001;
    }
    public static final class array {
        /**   
        <item>Hard</item>
        <item>Very Hard</item>
        
         */
        public static final int difficulty=0x7f060000;
    }
    public static final class attr {
    }
    public static final class color {
        /**  Retrieved via Resources.getColor() and friends. 
         */
        public static final int red=0x7f080000;
    }
    public static final class drawable {
        public static final int blue_bg=0x7f020000;
        public static final int btn_backgound=0x7f020001;
        public static final int btn_enabled=0x7f020002;
        public static final int icon=0x7f020003;
        public static final int icon2=0x7f020004;
        /**  Retrieved via Resources.getDrawable() and friends. 
         */
        public static final int red=0x7f020006;
        public static final int tundra_bg=0x7f020005;
        public static final int white=0x7f020007;
    }
    public static final class id {
        public static final int about_button=0x7f0a0014;
        public static final int about_content=0x7f0a0000;
        public static final int buttons=0x7f0a0002;
        public static final int clear=0x7f0a0005;
        public static final int continue_button=0x7f0a0011;
        public static final int exit_button=0x7f0a0015;
        public static final int frame=0x7f0a0001;
        public static final int hint=0x7f0a0006;
        public static final int keypad_1=0x7f0a0008;
        public static final int keypad_2=0x7f0a0009;
        public static final int keypad_3=0x7f0a000a;
        public static final int keypad_4=0x7f0a000b;
        public static final int keypad_5=0x7f0a000c;
        public static final int keypad_6=0x7f0a000d;
        public static final int keypad_7=0x7f0a000e;
        public static final int keypad_8=0x7f0a000f;
        public static final int keypad_9=0x7f0a0010;
        public static final int new_button=0x7f0a0012;
        public static final int options_button=0x7f0a0013;
        public static final int pause=0x7f0a0003;
        public static final int pencil=0x7f0a0007;
        public static final int solve=0x7f0a0004;
    }
    public static final class layout {
        public static final int about=0x7f030000;
        public static final int game=0x7f030001;
        public static final int keypad=0x7f030002;
        public static final int main=0x7f030003;
        public static final int preferences=0x7f030004;
        public static final int test=0x7f030005;
    }
    public static final class raw {
        public static final int yids_level_stats_screen=0x7f050000;
        public static final int yids_underground_level_2=0x7f050001;
    }
    public static final class string {
        public static final int about_label=0x7f090009;
        public static final int about_text=0x7f090025;
        public static final int about_title=0x7f090024;
        public static final int app_name=0x7f090003;
        public static final int cancel_label=0x7f090014;
        public static final int cell_cleared=0x7f090012;
        public static final int continue_label=0x7f090005;
        public static final int difficulty=0x7f090016;
        public static final int easy_label=0x7f090017;
        public static final int exit_label=0x7f09000a;
        public static final int game_saved_label=0x7f090008;
        public static final int game_solved=0x7f090011;
        public static final int game_title=0x7f09001e;
        public static final int hard_label=0x7f090019;
        public static final int keypad_title=0x7f090022;
        public static final int level=0x7f090015;
        public static final int main_title=0x7f090004;
        public static final int medium_label=0x7f090018;
        public static final int message_click_on_cell=0x7f09001b;
        public static final int message_click_on_cell_clear=0x7f09001d;
        public static final int message_click_on_cell_hint=0x7f09001c;
        public static final int new_game_label=0x7f090006;
        public static final int new_label=0x7f090021;
        public static final int no_moves_label=0x7f09001f;
        public static final int ok_label=0x7f090013;
        public static final int options_label=0x7f09000d;
        public static final int options_title=0x7f09000e;
        public static final int pause=0x7f09000b;
        public static final int play_music_label=0x7f09000f;
        /**  Options 
         */
        public static final int playmusic=0x7f090000;
        public static final int resume=0x7f09000c;
        public static final int save_game_label=0x7f090007;
        public static final int show_hints_label=0x7f090010;
        public static final int showincorrect=0x7f090002;
        public static final int showsolvable=0x7f090001;
        public static final int solve=0x7f090020;
        public static final int time=0x7f090023;
        public static final int very_hard_label=0x7f09001a;
    }
    public static final class style {
        public static final int Theme=0x7f070000;
    }
}
